### DISCUSSION TITLE
UE cannot connect to the internet

### DISCUSSION THREAD

**Discussion by marcohol1** [edgecomllc/eupf#542] [Q&A] [answered]
Hello everyone,

I want to deploy a docker container of eUPF and used the docker-compose template here (https://github.com/edgecomllc/eupf/blob/main/docs/install.md/#deploy-with-docker-compose). I use Open5GS core and the services are also deployed in docker containers. I also have an actual gNB and UE for testing. I have already made it worked with the normal UPF of Open5GS. However, when I swap out the UPF to the eUPF, I've noticed that the UE sends DNS queries but it does not go to the internet. I tried to ping 8.8.8.8 from the UE and it cannot go through the internet. However, when I try to ping eUPF using the UE, I see in Wireshark that it receives the ping and sends a reply but the reply is not received by the UE.

Here is part of the docker-file where eUPF is deployed:
```
 eupf:
    image: ghcr.io/edgecomllc/eupf:main
    privileged: true
    volumes:
      - /sys/fs/bpf:/sys/fs/bpf
    environment:
      - GIN_MODE=release
      - UPF_INTERFACE_NAME=eth0
      - UPF_XDP_ATTACH_MODE=generic
      - UPF_API_ADDRESS=:8081
      - UPF_PFCP_ADDRESS=:8805
      - UPF_METRICS_ADDRESS=:9091
      - UPF_PFCP_NODE_ID=172.18.0.20
      - UPF_N3_ADDRESS=172.18.0.20
    ulimits:
      memlock: -1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 2152:2152/udp
      - 8805:8805/udp
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
    networks:
      mynet1:
        ipv4_address: 172.18.0.20
    sysctls:
      - net.ipv4.conf.all.forwarding=1

  net-tools:
    image: praqma/network-multitool:alpine-extra@sha256:47b259d4463950f5c10d9c0bf63d9e71ec456618f5549a414afa0c04392e0ac1
    network_mode: host
    privileged: true
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - |
        ip ro add 10.45.0.0/16 via 172.18.0.20
        echo "done"
        tail -f /dev/null
```

Thank you very much and have a nice day!

Best regards,
Marco
