### ISSUE TITLE
Add simple slicing scenario support for free5gc

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#319]
**WHO**: MNO & Buisness customer
**WHAT**: MNO deploys separete slice for specific customer in order to provide independent network connectivity to customer's local resources.
**WHY**: APN routing is limited and complicated for MNO and requires equipment reconfiguration. Slicing looks more convenient and easy to deploy.

Configure deployment of slicing scenario with additional eUPF in separate slice. Choose slice based on specific STT/SD.

DoD:

- [x] 5GC deployed (Open5GS/Free5gc)
- [x] Additional eUPF deployed for separate slice
- [x] UE configured (one UERANSIM for both slices)
- [x] PDU session via default slice is up and running
- [x] PDU session via specific slice is up and running
- [ ] Decide how to combine several different scenarios in cluster

**Comment by PapaySail** [comment]
Referenced article [Select UPF based on S-NSSAI](https://github.com/s5uishida/open5gs_5gc_ueransim_snssai_upf_sample_config): Open5GS (SMF1 + UPF1) & (SMF2 + UPF2)

Orange-OpenSource/towards5gs-helm for free5gc current configs slice parameters:
AMF configmap:
```yaml
data:
  amfcfg.yaml: |
          snssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
      supportDnnList:
        - internet
```
