### ISSUE TITLE
Add simple slicing scenario support for open5gs

### ISSUE THREAD

**Issue by PapaySail** [edgecomllc/eupf#323]
From eupf created by [pirog-spb](https://github.com/pirog-spb): edgecomllc/eupf#319  

**WHO**: MNO & Buisness customer
**WHAT**: MNO deploys separete slice for specific customer in order to provide independent network connectivity to customer's local resources.
**WHY**: APN routing is limited and complicated for MNO and requires equipment reconfiguration. Slicing looks more convenient and easy to deploy.

Configure deployment of slicing scenario with additional eUPF in separate slice. Choose slice based on specific STT/SD.

DoD:

- [x] 5GC deployed (Open5GS)
- [x] Additional eUPF deployed for separate slice
- [x] UE configured (one UERANSIM for both slices)
- [x] PDU session via default slice is up and running
- [x] PDU session via specific slice is up and running
- [x] Decide how to combine several different scenarios in cluster

**Comment by PapaySail** [comment]
Target schema: Ext slice selection with SMF
![image](https://github.com/edgecomllc/eupf/assets/125686203/c83efc5e-07e4-45b5-97cc-b4aba4c134b6)

ℹ Referenced article [Select UPF based on S-NSSAI](https://github.com/s5uishida/open5gs_5gc_ueransim_snssai_upf_sample_config): Open5GS (SMF1 + UPF1) & (SMF2 + UPF2)
<details><summary>with schema</summary>
<p>

![image](https://github.com/s5uishida/open5gs_5gc_ueransim_snssai_upf_sample_config/blob/main/images/network-overview.png?raw=true)

</p>
</details>

**Comment by PapaySail** [comment]
Gradiant / [openverso-charts](https://github.com/Gradiant/openverso-charts) current configs slice parameters:
[5gSA-values.yaml](https://gradiant.github.io/openverso-charts/docs//open5gs-ueransim-gnb/5gSA-values.yaml)
```yaml
amf:
  config:
# ...
    plmnList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "0x111111"

nssf:
  config:
    nsiList:
      - nrf:
          hostname: ""  # if empty default is autogenerated open5gs svc fullname
          port: 7777
        sst: 1
        sd: "0x111111"

populate:
  enabled: true
  initCommands:
  - open5gs-dbctl add_ue_with_slice 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
  - open5gs-dbctl add_ue_with_slice 999700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111

smf:
  config:
    subnetList:
      - addr: 10.45.0.1/16
        dnn: internet
      - addr: 2001:db8:cafe::1/48
        dnn: internet
    pcrf:
      enabled: false
    upf:
      pfcp:
        hostname: edgecomllc-eupf-universal-chart
        port: 8805
``` 
So, will be needed to add for smf.config first slice only:
```yaml
    info:
      - s_nssai:
          - sst: 1
            sd: 111111
            dnn:
              - internet
        tai:
          - plmn_id:
              mcc: 999
              mnc: 70
            tac: 1
```
