### ISSUE TITLE
srsRAN research

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#403]
srsRAN project provides 4G/5G RAN software based solutions which could be used as complete RAN solution or together with virtual radio(ZeroMQ). 
I'm as a eUPF bundle vendor integrates with yet another virtual RAN solution in order to overcome current virtual RAN(UERANSIM) constrains and to verify eUPF interoperability with RAN.

Acceptance criteria:

- [x] Explore srsRAN project description
- [x] Create simple deployment with eUPF, Open5GS and srsRAN(ZeroMQ)
- [x] Fix deployment config: move srsRAN chart to separate repo
- [x] Present to team

**Comment by PapaySail** [comment]
## Explore srsRAN project description

Usable scenario is [ZeroMQ-based Setup](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#zeromq-based-setup)
some approach: @gradiant helm charts described in [Open5GS EPC and SRS LTE in kubernetes](https://gradiant.github.io/openverso-charts/open5gs-srslte.html)

**Comment by PapaySail** [comment]
## Create simple deployment with eUPF, Open5GS and srsRAN(ZeroMQ)

[gNB config](https://docs.srsran.com/projects/project/en/latest/_downloads/a7c34dbfee2b765503a81edd2f02ec22/gnb_zmq.yaml) from scenario [ZeroMQ-based Setup](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#zeromq-based-setup) is not fully compatible in syntax with the latest release 23.5. 
<details><summary>Working gNb config is:</summary>
<p>

```yaml
# This configuration file example shows how to configure the srsRAN Project gNB to allow srsUE to connect to it. 
# This specific example uses ZMQ in place of a USRP for the RF-frontend, and creates an FDD cell with 10 MHz bandwidth. 
# To run the srsRAN Project gNB with this config, use the following command: 
#   sudo ./gnb -c gnb_zmq.yaml

amf:
  addr: 10.233.22.229
  bind_addr: 10.233.64.35

rf_driver:
  device_driver: zmq                # The RF driver name.
  device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001,base_srate=11.52e6 # Optionally pass arguments to the selected RF driver.
  srate: 11.52                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 75                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 75                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 10         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).

log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: info                   # Logging level applied to all layers.
  hex_max_size: 0

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
``` 

</p>
</details> 

✔ Commit [srsran gnb helmcharts](https://github.com/edgecomllc/eupf/commit/1440cd71638cd198a88edd177e6012b354ed16ec) : gNB based on the latest release of srsRAN Project 23.5 connecting to Open5GS AMF
