### ISSUE TITLE
Deploy eUPF with OAI core

### ISSUE THREAD

**Issue by pirog-spb** [edgecomllc/eupf#473]
- [x] Try to connect eUPF with OAI in docker-compose
- [x] **Find out how to configure OAI SMF connection to UPF (!)**
- [x] Compare signalling messages with and without eUPF
- [ ] Research OAI site, habr, medium, reddit, linkedin to get mode info about deployment of OAI
- [x] Find compatible versions of UE-gNB-Core components
- [x] **Verify 0-scenario (!)**

**Comment by PapaySail** [comment]
OAI Full Stack 5G-NR L2 simulation with containers and a proxy started is in #340 
There is config parameters in docker-compose.yaml:
```yaml
    oai-smf:
        container_name: "l2sim-oai-smf"
        image: oaisoftwarealliance/oai-smf:v1.5.0
        environment:

            - UPF_IPV4_ADDRESS=192.168.71.134
            - UPF_FQDN_0=oai-spgwu
            - DISCOVER_UPF=yes
            - UE_MTU=1500
            # Only one slice is defined (1, 0xFFFFFF)
            - DNN_NI0=oai
            - TYPE0=IPv4
            - DNN_RANGE0=12.1.1.2 - 12.1.1.127
            - NSSAI_SST0=1

    oai-spgwu:
        container_name: "l2sim-oai-spgwu"
        image: oaisoftwarealliance/oai-spgwu-tiny:v1.5.0
        environment:
            - TZ=Europe/Paris
            - SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP=eth0
            - SGW_INTERFACE_NAME_FOR_SX=eth0
            - PGW_INTERFACE_NAME_FOR_SGI=eth0
            - NETWORK_UE_NAT_OPTION=yes
            - NETWORK_UE_IP=12.1.1.0/24
            - ENABLE_5G_FEATURES=yes
            - REGISTER_NRF=yes
            - USE_FQDN_NRF=yes
            - UPF_FQDN_5G=oai-spgwu
            - NRF_IPV4_ADDRESS=192.168.71.130
            - NRF_FQDN=oai-nrf
            # Only one slice is defined (1, 0xFFFFFF)
            - NSSAI_SST_0=1
            - NSSAI_SD_0=0xffffff
            - DNN_0=oai
        depends_on:
            - oai-nrf
            - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.71.134
            traffic_net:
                ipv4_address: 192.168.72.134

```

**Comment by PapaySail** [comment]
Re-checking how it works with original OAI  spgwu
I see - it use host's ens3 interface and IP addr for GTP tunnel

<details><summary>gNB's log:</summary>
<p>


```ruby
l2sim-oai-gnb  | 2023-11-09T06:39:12.767011327Z 4355918.969572 00000001 [GNB_APP] I default drx 0
l2sim-oai-gnb  | 2023-11-09T06:39:12.767047344Z 4355918.969586 00000001 [GNB_APP] I [gNB 0] gNB_app_register for instance 0
l2sim-oai-gnb  | 2023-11-09T06:39:12.767051606Z 4355918.969591 00000001 [UTIL] I Creating thread TASK_SCTP with affinity -1 and priority 50
l2sim-oai-gnb  | 2023-11-09T06:39:12.775436501Z 4355918.977871 00000001 [ITTI] I Created Posix thread TASK_SCTP
l2sim-oai-gnb  | 2023-11-09T06:39:12.775560259Z 4355918.978110 00000001 [X2AP] I X2AP is disabled.
l2sim-oai-gnb  | 2023-11-09T06:39:12.775683650Z 4355918.978240 00000001 [NGAP] D Configuration in the file: ens3.
l2sim-oai-gnb  | 2023-11-09T06:39:12.775725494Z 4355918.978297 00000001 [NGAP] D Configuration in the file: 188.120.232.247.
l2sim-oai-gnb  | 2023-11-09T06:39:12.775784022Z 4355918.978345 00000001 [UTIL] I Creating thread TASK_NGAP with affinity -1 and priority 50
l2sim-oai-gnb  | 2023-11-09T06:39:12.786292579Z 4355918.988703 00000016 [NGAP] I Starting NGAP layer
l2sim-oai-gnb  | 2023-11-09T06:39:12.786401141Z 4355918.988957 00000001 [ITTI] I Created Posix thread TASK_NGAP
l2sim-oai-gnb  | 2023-11-09T06:39:12.786464152Z 4355918.989021 00000001 [UTIL] I Creating thread TASK_GNB_APP with affinity -1 and priority 50
l2sim-oai-gnb  | 2023-11-09T06:39:12.787762871Z 4355918.989629 00000016 [NGAP] I Registered new gNB[0] and macro gNB id 3584
l2sim-oai-gnb  | 2023-11-09T06:39:12.787771276Z 4355918.989642 00000016 [NGAP] I [gNB 0] check the amf registration state
l2sim-oai-gnb  | 2023-11-09T06:39:12.789809407Z 4355918.992035 00000016 [NGAP] I 3584 -> 0000e000
l2sim-oai-gnb  | 2023-11-09T06:39:12.792499653Z 4355918.995019 00000016 [NGAP] I servedGUAMIs.list.count 1
l2sim-oai-gnb  | 2023-11-09T06:39:12.792521343Z 4355918.995038 00000016 [NGAP] I PLMNSupportList.list.count 1
l2sim-oai-gnb  | 2023-11-09T06:39:12.792525847Z 4355918.995041 00000016 [NGAP] I PLMNSupportList.list.count 1
l2sim-oai-gnb  | 2023-11-09T06:39:12.798248220Z 4355918.999736 00000001 [ITTI] I Created Posix thread TASK_GNB_APP
l2sim-oai-gnb  | 2023-11-09T06:39:12.798277941Z 4355918.999795 00000001 [NR_RRC] I Creating NR RRC gNB Task, that will also create TASKS
l2sim-oai-gnb  | 2023-11-09T06:39:12.798282055Z 4355918.999810 00000001 [UTIL] I Creating thread TASK_RRC_GNB with affinity -1 and priority 50
l2sim-oai-gnb  | 2023-11-09T06:39:12.800766216Z 4355919.000773 00000019 [GNB_APP] I [gNB 0] Received NGAP_REGISTER_GNB_CNF: associated AMF 1
l2sim-oai-gnb  | 2023-11-09T06:39:12.807547503Z 4355919.009281 00000001 [ITTI] I Created Posix thread TASK_RRC_GNB
l2sim-oai-gnb  | 2023-11-09T06:39:12.807815026Z 4355919.009454 00000001 [GTPU] I Configuring GTPu
l2sim-oai-gnb  | 2023-11-09T06:39:12.807821623Z 4355919.009525 00000001 [GTPU] I SA mode
l2sim-oai-gnb  | 2023-11-09T06:39:12.807842350Z 4355919.010165 00000001 [GTPU] I Configuring GTPu address : 188.120.232.247, port : 2152
l2sim-oai-gnb  | 2023-11-09T06:39:12.807846539Z 4355919.010203 00000001 [GTPU] I Initializing UDP for local address 188.120.232.247 with port 2152
l2sim-oai-gnb  | 2023-11-09T06:39:12.807850128Z 4355919.010243 0000001c [NR_RRC] I Entering main loop of NR_RRC message task
l2sim-oai-gnb  | 2023-11-09T06:39:12.807853418Z 4355919.010264 0000001c [NR_RRC] I Received F1 Setup Request from gNB_DU 3584 (gnb-l2sim-vnf) on assoc_id 0
l2sim-oai-gnb  | 2023-11-09T06:39:12.807856854Z 4355919.010284 00000001 [GTPU] I Created gtpu instance id: 101

```


</p>
</details>

**Comment by PapaySail** [comment]
Well, when our eupf container started, th interface is `l2sim-public`:
<details><summary>Details</summary>
<p>

```ruby
sergo@edgecom:~/gitlab/openairinterface5g/ci-scripts/yaml_files/5g_l2sim_tdd$ ip r get 192.168.71.134
192.168.71.134 dev l2sim-public src 192.168.71.129 uid 1002
    cache
sergo@edgecom:~/gitlab/openairinterface5g/ci-scripts/yaml_files/5g_l2sim_tdd$ ip r |grep  192.168.71
192.168.71.128/26 dev l2sim-public proto kernel scope link src 192.168.71.129
```

</p>
</details> 

So, I'll put it in the gNb config file:
``` ruby
nano ../../conf_files/gnb.sa.band78.106prb.l2sim.conf
    NETWORK_INTERFACES :
    {
        GNB_INTERFACE_NAME_FOR_NG_AMF            = "ens3";
        GNB_IPV4_ADDRESS_FOR_NG_AMF              = "188.120.232.247";
        GNB_INTERFACE_NAME_FOR_NGU               = "l2sim-public";
        GNB_IPV4_ADDRESS_FOR_NGU                 = "192.168.71.129";
        GNB_PORT_FOR_NGU                         = 2152; # Spec 2152
    };

sudo docker-compose up -d oai-gnb
```

Resulting log:
<details><summary>Details</summary>
<p>

```ruby
sudo docker-compose logs -tf  oai-gnb
...
l2sim-oai-gnb  | 2023-11-11T09:03:50.722368492Z 4537396.923772 00000001 [GTPU] I Configuring GTPu address : 192.168.71.129, port : 2152
l2sim-oai-gnb  | 2023-11-11T09:03:50.722387700Z 4537396.923779 00000001 [GTPU] I Initializing UDP for local address 192.168.71.129 with port 2152
l2sim-oai-gnb  | 2023-11-11T09:03:50.722391377Z 4537396.923834 00000001 [GTPU] I Created gtpu instance id: 101
l2sim-oai-gnb  | 2023-11-11T09:03:50.722394623Z 4537396.923841 00000001 [UTIL] I Creating thread TASK_GTPV1_U with affinity -1 and priority 50
l2sim-oai-gnb  | 2023-11-11T09:03:50.730501635Z 4537396.932866 00000001 [ITTI] I Created Posix thread TASK_GTPV1_U

```

</p>
</details>

**Comment by pirog-spb** [comment]
To make smf connect upf - disable UPF discovery:

```
    oai-smf:
        container_name: "l2sim-oai-smf"
        image: oaisoftwarealliance/oai-smf:v1.5.0
        environment:
            - ...
            - DISCOVER_UPF=no
            - ...

```

After that SMF try to connect to UPF. eUPF doesn't send Recovery Timestamp in response...
