### ISSUE TITLE
UE can't ping outide the NAT(internet for exemple)

### ISSUE THREAD

**Issue by kouamdo** [edgecomllc/eupf#499]
Hi , i'm building every network node(**open5gs**) using kubernetes and docker.That is the architecture, and i want to know why i can't ping to internet :

![image](https://github.com/edgecomllc/eupf/assets/39982727/e86480b7-06c5-4489-ae0d-666563fbea52)

i'm facing one issue , is that , the UE can't ping to outside the NAT , i have made some modification but nothing.

there , you can see that the PDU session was created : 

![image](https://github.com/edgecomllc/eupf/assets/39982727/981bbe27-4953-4b1c-8b6b-a284fdd3c505)

thenre is the SMF 

![image](https://github.com/edgecomllc/eupf/assets/39982727/52e35fa5-86e2-4ea6-8f6e-3ed28ff0f381)

that are the logs when i trying to ping outide the NAT : ( **ping -c1 google.com -I uesimtun0** ) 
eUPF :
![image](https://github.com/edgecomllc/eupf/assets/39982727/320aa445-7709-49b4-9f69-c7ab040b2564)
NAT gateway : 
![image](https://github.com/edgecomllc/eupf/assets/39982727/a9a95f55-1fea-4ee9-ac73-ebc677091100)

So , let me know where i have mistaken.

**Comment by pirog-spb** [comment]
Hi @kouamdo 

According to your last screenshort, GTP packets are sent to NAT GW instead of gNB.

eUPF uses kernel routing table to forward packets. So ensure that you have a route to gNB in the linux routing table(in container).

Here eUPF uses gw 172.16.0.1 to send packets to gNB(10.1.229.71).
![image](https://github.com/edgecomllc/eupf/assets/20152142/dd380021-3bd3-4623-a5be-12eac04c7a05)
Seems like gw 172.16.0.1 sent packets to NAT GW instead of gNB. Check routing on the host as well.

**Comment by kouamdo** [comment]
> they take this road because i have add this route : **ip r add default via 172.16.0.13 dev eth1** inside the eUPF container

**Comment by kouamdo** [comment]
that is the last one , after making some change : 
ù
![image](https://github.com/edgecomllc/eupf/assets/39982727/734c01df-0d37-4f31-bd88-572d0e46a433)

 and inside the eUPF : 

![image](https://github.com/edgecomllc/eupf/assets/39982727/07385a63-d342-40fa-a04b-7f46765ef6a8)

**Comment by pirog-spb** [comment]
@kouamdo Did you get `bpf_fib_lookup` result 7(BPF_FIB_LKUP_RET_NO_NEIGH) every time packet was processed?

**Comment by kouamdo** [comment]
> @kouamdo Did you get `bpf_fib_lookup` result 7(BPF_FIB_LKUP_RET_NO_NEIGH) every time packet was processed?

Yes , sure...
Nothing is working fine until now

**Comment by pirog-spb** [comment]
Usually, first packet gets BPF_FIB_LKUP_RET_NO_NEIGH because ARP table is empty. But subsequent packets are routed well.

Try to ping IP-address manually(to fill arp table) form eupf container and check routing after that.

**Comment by kouamdo** [comment]
What about using of ip rule or vrf ?
Do you think that it can resolve the problem?

**Comment by pirog-spb** [comment]
We have to localize the problem first. My point - the problem is in routing settings.

The simplest routing config in eupf would be as follows:
```
iptables -A FORWARD -j ACCEPT
echo "1200 n6if" >> /etc/iproute2/rt_tables
ip rule add from 10.45.0.0/16 table n6if
ip route add default via 172.16.0.13 dev eth1 table n6if
```

So, ip rule for N3->N6 packets and generic default route(not shown here) for N3->N6 packets

**Comment by kouamdo** [comment]
let me know if this content is sufficient 
![image](https://github.com/edgecomllc/eupf/assets/39982727/6230b022-3869-4ba5-95c6-51bcada453a0)

i'mgetting another type of errors :  `bpf_fib_lookup` result 4

![image](https://github.com/edgecomllc/eupf/assets/39982727/91b81200-2449-43c8-95c6-8251bbb80734)

**Comment by kouamdo** [comment]
it is fine now , but let me show you some informations that i have : 

![image](https://github.com/edgecomllc/eupf/assets/39982727/49944009-6c55-4ad0-896c-a6f01bb888e7)

there is the docker compose file : 

```
version: '2.4'

services:
  eupf:
    image: local/eupf:latest
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /etc/iproute2/;
        echo "1000 n6if" >> /etc/iproute2/rt_tables;
        echo 1 > /proc/sys/net/ipv4/ip_forward;
        ip rule add from 10.33.0.0/16 table n6if;
        ip route add default via 172.16.0.13 dev eth2 table n6if &&
        sh /app/bin/entrypoint.sh --config /app/bin/eupf_config.yml
    privileged: true
    environment:
      - GIN_MODE=release

    volumes:
      - /sys/fs/bpf:/sys/fs/bpf
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - ./eupf_config.yml:/app/bin/eupf_config.yml
    ulimits:
      memlock: -1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 2152:2152/udp
      - 8805:8805/udp
      - 8081:8081
      - 9091:9091
    restart: unless-stopped
    networks:
      n3:
        ipv4_address: 172.18.0.12
      n4:
        ipv4_address: 172.19.0.12
      n6:
        ipv4_address: 172.16.0.12
    sysctls:
      - net.ipv4.conf.all.forwarding=1

  nat-dn:
    image: ubuntu:focal
    privileged: true
    restart: unless-stopped
    networks:
      n6:
        ipv4_address: 172.16.0.13
    command:
      - /bin/sh
      - -c
      - |
        apt update && apt install -y iproute2 tcpdump iptables
        sysctl -w net.ipv6.conf.all.disable_ipv6=1
        echo 1 > /proc/sys/net/ipv4/ip_forward
        iptables -t nat -A POSTROUTING -s 10.33.0.0/16 -j MASQUERADE
        ip ro add 10.33.0.0/16 via 172.16.0.12 dev eth0
        echo "done"
        tail -f /dev/null

networks:
  n3:
    external: true
  n4:
    external: true
  n6:
    external: true
```

that's about route 

![image](https://github.com/edgecomllc/eupf/assets/39982727/d73227f7-081e-4e75-be04-63db6f780d63)


that's inside the DN : 

![image](https://github.com/edgecomllc/eupf/assets/39982727/16efe3c8-e27f-4b62-bdd6-f1fcdd728bf3)
